name: venv_loadinsight
dependencies:
  - python=3.7.3
  - pandas
  - numpy
  - matplotlib
  - pip:
    - boto3
    - requests
    - Pillow
    - awscli
    - djangorestframework
    - djangorestframework-jwt
