name: venv_loadinsight
dependencies:
  - python=3.7.3
  - pandas
  - numpy
  - matplotlib
  - pip
  - pip:
    - boto3
    - requests
    - Pillow
    - awscli
    - djangorestframework
    - djangorestframework-jwt
    - dj-database-url
    - django-rest-auth
    - django-allauth
