version: 2
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:xenial
    steps:
      - checkout
          name: Make sure Python 3.6 is properly setup
          command: |
            sudo apt-get install software-properties-common python-software-properties --yes
            sudo add-apt-repository -y ppa:deadsnakes/ppa
            sudo apt update
            sudo apt-get install python3-dev
            sudo apt install python3.6            
            sudo update-alternatives --install /usr/bin/python python /usr/bin/python3.6 1
            sudo update-alternatives --set python /usr/bin/python3.6            
      - run:
          name: Get Pip and install Python Dependencies
          command: |
            sudo apt-get -y install python3-pip
            sudo pip3 install matplotlib
      - run:
          name: Run test
          command: |
            cd source
            python LoadInsight.py
      - store_artifacts:
          path: /home/circleci/project/remote
          destination: /output
