version: 2
jobs:
  build:
    docker:
      - image: continuumio/miniconda3

    working_directory: ~/loadinsight
    steps:
      - checkout
      # - run:
      #     name: Install Conda
      #     command: 
      #       wget https://repo.anaconda.com/archive/Anaconda3-2019.10-Linux-x86_64.sh && bash Anaconda3-2019.10-Linux-x86_64.sh -b && rm Anaconda3-2019.10-Linux-x86_64.sh
      #       echo "PATH=~/anaconda3/bin:$PATH" > ~/.bashrc && source ~/.bashrc
      - run:
          name: Install Node.js
          command:
            wget https://deb.nodesource.com/setup_13.x
            && chmod +x setup_13.x
            && bash setup_13.x
            && rm setup_13.x
            && apt-get install -y nodejs
      - run:
          name: Install Postgres Client
          command:
            echo "deb http://apt.postgresql.org/pub/repos/apt/ buster-pgdg main" > /etc/apt/sources.list.d/pgdg.list
            && wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add -
            && apt-get update
            && apt-get install -y postgresql-client-11 libpq-dev && rm -rf /var/lib/apt/lists/*
      - run:
          name: Build web code
          working_directory: web/frontend/app
          command:
            npm install .
            && npm run build
      - run: 
          name: Run Unit Tests
          command: python -m unittest
          
  deploy:
    docker:
      - image: circleci/python:3.7.4

    working_directory: ~/loadinsight
    steps:
      - run: |
          echo "Hello, I'm not deploying yet, but that's ok, I will soon..."

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: 
                - master
                - cmu
