version: 2
jobs:
  build:
    docker:
      - image: slacgismo/circleci_python37_base
    steps:
      - checkout
      - run:
          name: Install libraries
          command: |
            sudo apt-get -y install python3-pip
            sudo pip3 install matplotlib
      - run:
          name: Run test
          command: |
            cd source
            python selftest.py
      - store_artifacts:
          path: /home/circleci/project/source/remote
          destination: /output
