version: '2'

services:
  app:
    environment:
      # TODO: Please modify the database URL accordingly 
      DATABASE_URL: postgres://USER:PASSWORD@HOST:PORT/NAME
      DJANGO_MANAGEPY_MIGRATE: "on"
    build:
      context: . 
      dockerfile: ./Dockerfile
    image: loadinsight:1.0
    ports:
      - "8000:8000"